- optimiser: Adam
  learning_rate: 0.01
  hidden_layer_width: 8
  hidden_layer_depth: 5
- optimiser: Adam
  learning_rate: 0.001
  hidden_layer_width: 8
  hidden_layer_depth: 4
- optimiser: SGD
  learning_rate: 0.1
  hidden_layer_width: 6
  hidden_layer_depth: 4
- optimiser: SGD
  learning_rate: 0.01
  hidden_layer_width: 8
  hidden_layer_depth: 5
- optimiser: SGD
  learning_rate: 0.01
  hidden_layer_width: 8
  hidden_layer_depth: 3
- optimiser: Adam
  learning_rate: 0.01
  hidden_layer_width: 8
  hidden_layer_depth: 5
- optimiser: Adam
  learning_rate: 0.1
  hidden_layer_width: 7
  hidden_layer_depth: 4
- optimiser: SGD
  learning_rate: 0.001
  hidden_layer_width: 7
  hidden_layer_depth: 5
- optimiser: Adagrad
  learning_rate: 0.01
  hidden_layer_width: 8
  hidden_layer_depth: 3
- optimiser: Adam
  learning_rate: 0.1
  hidden_layer_width: 8
  hidden_layer_depth: 5
- optimiser: Adam
  learning_rate: 0.001
  hidden_layer_width: 6
  hidden_layer_depth: 5
- optimiser: Adam
  learning_rate: 0.001
  hidden_layer_width: 7
  hidden_layer_depth: 3
- optimiser: SGD
  learning_rate: 0.01
  hidden_layer_width: 6
  hidden_layer_depth: 5
- optimiser: Adam
  learning_rate: 0.1
  hidden_layer_width: 7
  hidden_layer_depth: 3
- optimiser: SGD
  learning_rate: 0.1
  hidden_layer_width: 6
  hidden_layer_depth: 3